/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package xanxa.objectfight.uiStartLevelEnd;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author wenfi
 */
public class IniciarJuego extends javax.swing.JDialog {
     private Image imagenFondo;
     private InterfazInformacion informacion;
    public IniciarJuego(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Cargar la imagen de fondo desde la carpeta "src/EstadosDelJuego"
        this.imagenFondo = new ImageIcon(getClass().getResource("/EstadosDelJuego/InicioJuego.jpg")).getImage();

        // Usar un JPanel personalizado para el fondo del diálogo
        JPanel panelFondo = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (imagenFondo != null) {
                    g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
                }
            }
        };

        // Configura el panel de fondo como el contenedor principal
        setContentPane(panelFondo);
        panelFondo.setLayout(null); // Usamos null layout para manipular los componentes manualmente


        // Establecer la fuente para los botones
        Font buttonFont = new Font("Segoe UI", Font.PLAIN, 24);
        btnIniciar.setFont(buttonFont);
        btnInformacion.setFont(buttonFont);
        btnSalir.setFont(buttonFont);

        // Establecer el tamaño de los botones
        Dimension buttonSize = new Dimension(300, 60);
        btnIniciar.setPreferredSize(buttonSize);
        btnInformacion.setPreferredSize(buttonSize);
        btnSalir.setPreferredSize(buttonSize);

        // Agregar los botones al panel
        panelFondo.add(btnIniciar);
        panelFondo.add(btnInformacion);
        panelFondo.add(btnSalir);

        // Establecer el tamaño del JDialog como un porcentaje de la pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int dialogWidth = (int) (screenSize.width * 0.5);
        int dialogHeight = (int) (screenSize.height * 0.5);
        setSize(dialogWidth, dialogHeight);

        // Centrar el JDialog en la pantalla
        setLocationRelativeTo(null);

        // Ajustar la posición de los botones después de que el diálogo tenga un tamaño
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                adjustButtonPositions();
            }
        });
    }

    private void adjustButtonPositions() {
        int panelWidth = getContentPane().getWidth();
        int panelHeight = getContentPane().getHeight();

        int buttonWidth = btnIniciar.getPreferredSize().width;
        int buttonHeight = btnIniciar.getPreferredSize().height;
        int totalButtonsHeight = buttonHeight * 3 + 20 * 2; // 3 botones + 2 espacios

        int startY = (panelHeight - totalButtonsHeight) / 2;
        int centerX = (panelWidth - buttonWidth) / 2;

        btnIniciar.setBounds(centerX, startY, buttonWidth, buttonHeight);
        btnInformacion.setBounds(centerX, startY + buttonHeight + 20, buttonWidth, buttonHeight);
        btnSalir.setBounds(centerX, startY + (buttonHeight + 20) * 2, buttonWidth, buttonHeight);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciar = new javax.swing.JToggleButton();
        btnSalir = new javax.swing.JToggleButton();
        btnInformacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnIniciar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnIniciar.setText("INICIAR JUEGO");
        btnIniciar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnInformacion.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        btnInformacion.setText("INFORMACION");
        btnInformacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionActionPerformed
     SwingUtilities.invokeLater(new Runnable() {
        @Override
        public void run() {
            // Obtener el Frame principal
            java.awt.Frame parentFrame = javax.swing.JOptionPane.getFrameForComponent(IniciarJuego.this);
            InterfazInformacion informacion = new InterfazInformacion(parentFrame, true);
            informacion.setVisible(true);
        }
    });
        
    }//GEN-LAST:event_btnInformacionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // Cerrar la aplicación
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
       // Cerrar la ventana actual
        this.dispose();

        // Iniciar el juego (xanxa.objectfight.Main)
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    xanxa.objectfight.Main.main(new String[]{});
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IniciarJuego dialog = new IniciarJuego(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInformacion;
    private javax.swing.JToggleButton btnIniciar;
    private javax.swing.JToggleButton btnSalir;
    // End of variables declaration//GEN-END:variables
}
